// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/Bolshevichok/dronedelivery/internal/models"
)

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// GetAvailableDrones provides a mock function with given fields: ctx, launchBaseID
func (_m *Storage) GetAvailableDrones(ctx context.Context, launchBaseID uint64) ([]*models.Drone, error) {
	ret := _m.Called(ctx, launchBaseID)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableDrones")
	}

	var r0 []*models.Drone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]*models.Drone, error)); ok {
		return rf(ctx, launchBaseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []*models.Drone); ok {
		r0 = rf(ctx, launchBaseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Drone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, launchBaseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDronesByIDs provides a mock function with given fields: ctx, IDs
func (_m *Storage) GetDronesByIDs(ctx context.Context, IDs []uint64) ([]*models.Drone, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetDronesByIDs")
	}

	var r0 []*models.Drone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.Drone, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.Drone); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Drone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLaunchBasesByIDs provides a mock function with given fields: ctx, IDs
func (_m *Storage) GetLaunchBasesByIDs(ctx context.Context, IDs []uint64) ([]*models.LaunchBase, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetLaunchBasesByIDs")
	}

	var r0 []*models.LaunchBase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.LaunchBase, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.LaunchBase); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LaunchBase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMissionDronesByMissionID provides a mock function with given fields: ctx, missionID
func (_m *Storage) GetMissionDronesByMissionID(ctx context.Context, missionID uint64) ([]*models.MissionDrone, error) {
	ret := _m.Called(ctx, missionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMissionDronesByMissionID")
	}

	var r0 []*models.MissionDrone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]*models.MissionDrone, error)); ok {
		return rf(ctx, missionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []*models.MissionDrone); ok {
		r0 = rf(ctx, missionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MissionDrone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, missionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMissionDronesByMissionIDs provides a mock function with given fields: ctx, missionIDs
func (_m *Storage) GetMissionDronesByMissionIDs(ctx context.Context, missionIDs []uint64) ([]*models.MissionDrone, error) {
	ret := _m.Called(ctx, missionIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetMissionDronesByMissionIDs")
	}

	var r0 []*models.MissionDrone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.MissionDrone, error)); ok {
		return rf(ctx, missionIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.MissionDrone); ok {
		r0 = rf(ctx, missionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MissionDrone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, missionIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMissionsByIDs provides a mock function with given fields: ctx, IDs
func (_m *Storage) GetMissionsByIDs(ctx context.Context, IDs []uint64) ([]*models.Mission, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetMissionsByIDs")
	}

	var r0 []*models.Mission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.Mission, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.Mission); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Mission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOperatorsByIDs provides a mock function with given fields: ctx, IDs
func (_m *Storage) GetOperatorsByIDs(ctx context.Context, IDs []uint64) ([]*models.Operator, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetOperatorsByIDs")
	}

	var r0 []*models.Operator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.Operator, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.Operator); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Operator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateMissionStatus provides a mock function with given fields: ctx, missionID, status
func (_m *Storage) UpdateMissionStatus(ctx context.Context, missionID uint64, status string) error {
	ret := _m.Called(ctx, missionID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMissionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) error); ok {
		r0 = rf(ctx, missionID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertDrones provides a mock function with given fields: ctx, drones
func (_m *Storage) UpsertDrones(ctx context.Context, drones []*models.Drone) error {
	ret := _m.Called(ctx, drones)

	if len(ret) == 0 {
		panic("no return value specified for UpsertDrones")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Drone) error); ok {
		r0 = rf(ctx, drones)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertLaunchBases provides a mock function with given fields: ctx, launchBases
func (_m *Storage) UpsertLaunchBases(ctx context.Context, launchBases []*models.LaunchBase) error {
	ret := _m.Called(ctx, launchBases)

	if len(ret) == 0 {
		panic("no return value specified for UpsertLaunchBases")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.LaunchBase) error); ok {
		r0 = rf(ctx, launchBases)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertMissionDrones provides a mock function with given fields: ctx, missionDrones
func (_m *Storage) UpsertMissionDrones(ctx context.Context, missionDrones []*models.MissionDrone) error {
	ret := _m.Called(ctx, missionDrones)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMissionDrones")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.MissionDrone) error); ok {
		r0 = rf(ctx, missionDrones)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertMissions provides a mock function with given fields: ctx, missions
func (_m *Storage) UpsertMissions(ctx context.Context, missions []*models.Mission) ([]*models.Mission, error) {
	ret := _m.Called(ctx, missions)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMissions")
	}

	var r0 []*models.Mission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Mission) ([]*models.Mission, error)); ok {
		return rf(ctx, missions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Mission) []*models.Mission); ok {
		r0 = rf(ctx, missions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Mission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*models.Mission) error); ok {
		r1 = rf(ctx, missions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertOperators provides a mock function with given fields: ctx, operators
func (_m *Storage) UpsertOperators(ctx context.Context, operators []*models.Operator) error {
	ret := _m.Called(ctx, operators)

	if len(ret) == 0 {
		panic("no return value specified for UpsertOperators")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Operator) error); ok {
		r0 = rf(ctx, operators)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStorage creates a new instance of Storage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
