// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: mission/v1/mission.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateMissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperatorId     uint64                 `protobuf:"varint,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	LaunchBaseId   uint64                 `protobuf:"varint,2,opt,name=launch_base_id,json=launchBaseId,proto3" json:"launch_base_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DestinationLat float64                `protobuf:"fixed64,4,opt,name=destination_lat,json=destinationLat,proto3" json:"destination_lat,omitempty"`
	DestinationLon float64                `protobuf:"fixed64,5,opt,name=destination_lon,json=destinationLon,proto3" json:"destination_lon,omitempty"`
	DestinationAlt float64                `protobuf:"fixed64,6,opt,name=destination_alt,json=destinationAlt,proto3" json:"destination_alt,omitempty"`
	PayloadKg      float64                `protobuf:"fixed64,7,opt,name=payload_kg,json=payloadKg,proto3" json:"payload_kg,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMissionRequest) Reset() {
	*x = CreateMissionRequest{}
	mi := &file_mission_v1_mission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMissionRequest) ProtoMessage() {}

func (x *CreateMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMissionRequest.ProtoReflect.Descriptor instead.
func (*CreateMissionRequest) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{0}
}

func (x *CreateMissionRequest) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *CreateMissionRequest) GetLaunchBaseId() uint64 {
	if x != nil {
		return x.LaunchBaseId
	}
	return 0
}

func (x *CreateMissionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateMissionRequest) GetDestinationLat() float64 {
	if x != nil {
		return x.DestinationLat
	}
	return 0
}

func (x *CreateMissionRequest) GetDestinationLon() float64 {
	if x != nil {
		return x.DestinationLon
	}
	return 0
}

func (x *CreateMissionRequest) GetDestinationAlt() float64 {
	if x != nil {
		return x.DestinationAlt
	}
	return 0
}

func (x *CreateMissionRequest) GetPayloadKg() float64 {
	if x != nil {
		return x.PayloadKg
	}
	return 0
}

type CreateMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMissionResponse) Reset() {
	*x = CreateMissionResponse{}
	mi := &file_mission_v1_mission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMissionResponse) ProtoMessage() {}

func (x *CreateMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMissionResponse.ProtoReflect.Descriptor instead.
func (*CreateMissionResponse) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMissionResponse) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

type GetMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionRequest) Reset() {
	*x = GetMissionRequest{}
	mi := &file_mission_v1_mission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionRequest) ProtoMessage() {}

func (x *GetMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionRequest.ProtoReflect.Descriptor instead.
func (*GetMissionRequest) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{2}
}

func (x *GetMissionRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

type GetMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       *Mission               `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionResponse) Reset() {
	*x = GetMissionResponse{}
	mi := &file_mission_v1_mission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionResponse) ProtoMessage() {}

func (x *GetMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionResponse.ProtoReflect.Descriptor instead.
func (*GetMissionResponse) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{3}
}

func (x *GetMissionResponse) GetMission() *Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

type ListMissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissionsRequest) Reset() {
	*x = ListMissionsRequest{}
	mi := &file_mission_v1_mission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissionsRequest) ProtoMessage() {}

func (x *ListMissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissionsRequest.ProtoReflect.Descriptor instead.
func (*ListMissionsRequest) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{4}
}

type ListMissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Missions      []*Mission             `protobuf:"bytes,1,rep,name=missions,proto3" json:"missions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMissionsResponse) Reset() {
	*x = ListMissionsResponse{}
	mi := &file_mission_v1_mission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMissionsResponse) ProtoMessage() {}

func (x *ListMissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMissionsResponse.ProtoReflect.Descriptor instead.
func (*ListMissionsResponse) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{5}
}

func (x *ListMissionsResponse) GetMissions() []*Mission {
	if x != nil {
		return x.Missions
	}
	return nil
}

type GetMissionTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionTelemetryRequest) Reset() {
	*x = GetMissionTelemetryRequest{}
	mi := &file_mission_v1_mission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionTelemetryRequest) ProtoMessage() {}

func (x *GetMissionTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionTelemetryRequest.ProtoReflect.Descriptor instead.
func (*GetMissionTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{6}
}

func (x *GetMissionTelemetryRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

type GetMissionTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telemetry     *Telemetry             `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionTelemetryResponse) Reset() {
	*x = GetMissionTelemetryResponse{}
	mi := &file_mission_v1_mission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionTelemetryResponse) ProtoMessage() {}

func (x *GetMissionTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionTelemetryResponse.ProtoReflect.Descriptor instead.
func (*GetMissionTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{7}
}

func (x *GetMissionTelemetryResponse) GetTelemetry() *Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

type WatchMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchMissionRequest) Reset() {
	*x = WatchMissionRequest{}
	mi := &file_mission_v1_mission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMissionRequest) ProtoMessage() {}

func (x *WatchMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMissionRequest.ProtoReflect.Descriptor instead.
func (*WatchMissionRequest) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{8}
}

func (x *WatchMissionRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

type MissionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Telemetry     *Telemetry             `protobuf:"bytes,2,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MissionUpdate) Reset() {
	*x = MissionUpdate{}
	mi := &file_mission_v1_mission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionUpdate) ProtoMessage() {}

func (x *MissionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionUpdate.ProtoReflect.Descriptor instead.
func (*MissionUpdate) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{9}
}

func (x *MissionUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MissionUpdate) GetTelemetry() *Telemetry {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

func (x *MissionUpdate) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Mission struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OperatorId     uint64                 `protobuf:"varint,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	LaunchBaseId   uint64                 `protobuf:"varint,3,opt,name=launch_base_id,json=launchBaseId,proto3" json:"launch_base_id,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	DestinationLat float64                `protobuf:"fixed64,5,opt,name=destination_lat,json=destinationLat,proto3" json:"destination_lat,omitempty"`
	DestinationLon float64                `protobuf:"fixed64,6,opt,name=destination_lon,json=destinationLon,proto3" json:"destination_lon,omitempty"`
	DestinationAlt float64                `protobuf:"fixed64,7,opt,name=destination_alt,json=destinationAlt,proto3" json:"destination_alt,omitempty"`
	PayloadKg      float64                `protobuf:"fixed64,8,opt,name=payload_kg,json=payloadKg,proto3" json:"payload_kg,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Operator       *Operator              `protobuf:"bytes,10,opt,name=operator,proto3" json:"operator,omitempty"`
	LaunchBase     *LaunchBase            `protobuf:"bytes,11,opt,name=launch_base,json=launchBase,proto3" json:"launch_base,omitempty"`
	Drones         []*Drone               `protobuf:"bytes,12,rep,name=drones,proto3" json:"drones,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Mission) Reset() {
	*x = Mission{}
	mi := &file_mission_v1_mission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{10}
}

func (x *Mission) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mission) GetOperatorId() uint64 {
	if x != nil {
		return x.OperatorId
	}
	return 0
}

func (x *Mission) GetLaunchBaseId() uint64 {
	if x != nil {
		return x.LaunchBaseId
	}
	return 0
}

func (x *Mission) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Mission) GetDestinationLat() float64 {
	if x != nil {
		return x.DestinationLat
	}
	return 0
}

func (x *Mission) GetDestinationLon() float64 {
	if x != nil {
		return x.DestinationLon
	}
	return 0
}

func (x *Mission) GetDestinationAlt() float64 {
	if x != nil {
		return x.DestinationAlt
	}
	return 0
}

func (x *Mission) GetPayloadKg() float64 {
	if x != nil {
		return x.PayloadKg
	}
	return 0
}

func (x *Mission) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Mission) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *Mission) GetLaunchBase() *LaunchBase {
	if x != nil {
		return x.LaunchBase
	}
	return nil
}

func (x *Mission) GetDrones() []*Drone {
	if x != nil {
		return x.Drones
	}
	return nil
}

type Operator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operator) Reset() {
	*x = Operator{}
	mi := &file_mission_v1_mission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{11}
}

func (x *Operator) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Operator) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Operator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operator) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type LaunchBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,5,opt,name=alt,proto3" json:"alt,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchBase) Reset() {
	*x = LaunchBase{}
	mi := &file_mission_v1_mission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchBase) ProtoMessage() {}

func (x *LaunchBase) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchBase.ProtoReflect.Descriptor instead.
func (*LaunchBase) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{12}
}

func (x *LaunchBase) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LaunchBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LaunchBase) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LaunchBase) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *LaunchBase) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *LaunchBase) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Drone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	LaunchBaseId  uint64                 `protobuf:"varint,5,opt,name=launch_base_id,json=launchBaseId,proto3" json:"launch_base_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drone) Reset() {
	*x = Drone{}
	mi := &file_mission_v1_mission_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drone) ProtoMessage() {}

func (x *Drone) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drone.ProtoReflect.Descriptor instead.
func (*Drone) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{13}
}

func (x *Drone) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Drone) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Drone) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Drone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Drone) GetLaunchBaseId() uint64 {
	if x != nil {
		return x.LaunchBaseId
	}
	return 0
}

func (x *Drone) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneId       uint64                 `protobuf:"varint,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,4,opt,name=alt,proto3" json:"alt,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_mission_v1_mission_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_mission_v1_mission_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_mission_v1_mission_proto_rawDescGZIP(), []int{14}
}

func (x *Telemetry) GetDroneId() uint64 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *Telemetry) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Telemetry) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Telemetry) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Telemetry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_mission_v1_mission_proto protoreflect.FileDescriptor

const file_mission_v1_mission_proto_rawDesc = "" +
	"\n" +
	"\x18mission/v1/mission.proto\x12\n" +
	"mission.v1\"\x8f\x02\n" +
	"\x14CreateMissionRequest\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\x04R\n" +
	"operatorId\x12$\n" +
	"\x0elaunch_base_id\x18\x02 \x01(\x04R\flaunchBaseId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12'\n" +
	"\x0fdestination_lat\x18\x04 \x01(\x01R\x0edestinationLat\x12'\n" +
	"\x0fdestination_lon\x18\x05 \x01(\x01R\x0edestinationLon\x12'\n" +
	"\x0fdestination_alt\x18\x06 \x01(\x01R\x0edestinationAlt\x12\x1d\n" +
	"\n" +
	"payload_kg\x18\a \x01(\x01R\tpayloadKg\"6\n" +
	"\x15CreateMissionResponse\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\"2\n" +
	"\x11GetMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\"C\n" +
	"\x12GetMissionResponse\x12-\n" +
	"\amission\x18\x01 \x01(\v2\x13.mission.v1.MissionR\amission\"\x15\n" +
	"\x13ListMissionsRequest\"G\n" +
	"\x14ListMissionsResponse\x12/\n" +
	"\bmissions\x18\x01 \x03(\v2\x13.mission.v1.MissionR\bmissions\";\n" +
	"\x1aGetMissionTelemetryRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\"R\n" +
	"\x1bGetMissionTelemetryResponse\x123\n" +
	"\ttelemetry\x18\x01 \x01(\v2\x15.mission.v1.TelemetryR\ttelemetry\"4\n" +
	"\x13WatchMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\"z\n" +
	"\rMissionUpdate\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x123\n" +
	"\ttelemetry\x18\x02 \x01(\v2\x15.mission.v1.TelemetryR\ttelemetry\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xc7\x03\n" +
	"\aMission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\x04R\n" +
	"operatorId\x12$\n" +
	"\x0elaunch_base_id\x18\x03 \x01(\x04R\flaunchBaseId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12'\n" +
	"\x0fdestination_lat\x18\x05 \x01(\x01R\x0edestinationLat\x12'\n" +
	"\x0fdestination_lon\x18\x06 \x01(\x01R\x0edestinationLon\x12'\n" +
	"\x0fdestination_alt\x18\a \x01(\x01R\x0edestinationAlt\x12\x1d\n" +
	"\n" +
	"payload_kg\x18\b \x01(\x01R\tpayloadKg\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x120\n" +
	"\boperator\x18\n" +
	" \x01(\v2\x14.mission.v1.OperatorR\boperator\x127\n" +
	"\vlaunch_base\x18\v \x01(\v2\x16.mission.v1.LaunchBaseR\n" +
	"launchBase\x12)\n" +
	"\x06drones\x18\f \x03(\v2\x11.mission.v1.DroneR\x06drones\"c\n" +
	"\bOperator\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\x85\x01\n" +
	"\n" +
	"LaunchBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x05 \x01(\x01R\x03alt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\xa2\x01\n" +
	"\x05Drone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12$\n" +
	"\x0elaunch_base_id\x18\x05 \x01(\x04R\flaunchBaseId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"z\n" +
	"\tTelemetry\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\x04R\adroneId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x04 \x01(\x01R\x03alt\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp2\xbc\x03\n" +
	"\x0eMissionService\x12T\n" +
	"\rCreateMission\x12 .mission.v1.CreateMissionRequest\x1a!.mission.v1.CreateMissionResponse\x12K\n" +
	"\n" +
	"GetMission\x12\x1d.mission.v1.GetMissionRequest\x1a\x1e.mission.v1.GetMissionResponse\x12Q\n" +
	"\fListMissions\x12\x1f.mission.v1.ListMissionsRequest\x1a .mission.v1.ListMissionsResponse\x12f\n" +
	"\x13GetMissionTelemetry\x12&.mission.v1.GetMissionTelemetryRequest\x1a'.mission.v1.GetMissionTelemetryResponse\x12L\n" +
	"\fWatchMission\x12\x1f.mission.v1.WatchMissionRequest\x1a\x19.mission.v1.MissionUpdate0\x01B>Z<github.com/Bolshevichok/dronedelivery/internal/pb/mission/v1b\x06proto3"

var (
	file_mission_v1_mission_proto_rawDescOnce sync.Once
	file_mission_v1_mission_proto_rawDescData []byte
)

func file_mission_v1_mission_proto_rawDescGZIP() []byte {
	file_mission_v1_mission_proto_rawDescOnce.Do(func() {
		file_mission_v1_mission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mission_v1_mission_proto_rawDesc), len(file_mission_v1_mission_proto_rawDesc)))
	})
	return file_mission_v1_mission_proto_rawDescData
}

var file_mission_v1_mission_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_mission_v1_mission_proto_goTypes = []any{
	(*CreateMissionRequest)(nil),        // 0: mission.v1.CreateMissionRequest
	(*CreateMissionResponse)(nil),       // 1: mission.v1.CreateMissionResponse
	(*GetMissionRequest)(nil),           // 2: mission.v1.GetMissionRequest
	(*GetMissionResponse)(nil),          // 3: mission.v1.GetMissionResponse
	(*ListMissionsRequest)(nil),         // 4: mission.v1.ListMissionsRequest
	(*ListMissionsResponse)(nil),        // 5: mission.v1.ListMissionsResponse
	(*GetMissionTelemetryRequest)(nil),  // 6: mission.v1.GetMissionTelemetryRequest
	(*GetMissionTelemetryResponse)(nil), // 7: mission.v1.GetMissionTelemetryResponse
	(*WatchMissionRequest)(nil),         // 8: mission.v1.WatchMissionRequest
	(*MissionUpdate)(nil),               // 9: mission.v1.MissionUpdate
	(*Mission)(nil),                     // 10: mission.v1.Mission
	(*Operator)(nil),                    // 11: mission.v1.Operator
	(*LaunchBase)(nil),                  // 12: mission.v1.LaunchBase
	(*Drone)(nil),                       // 13: mission.v1.Drone
	(*Telemetry)(nil),                   // 14: mission.v1.Telemetry
}
var file_mission_v1_mission_proto_depIdxs = []int32{
	10, // 0: mission.v1.GetMissionResponse.mission:type_name -> mission.v1.Mission
	10, // 1: mission.v1.ListMissionsResponse.missions:type_name -> mission.v1.Mission
	14, // 2: mission.v1.GetMissionTelemetryResponse.telemetry:type_name -> mission.v1.Telemetry
	14, // 3: mission.v1.MissionUpdate.telemetry:type_name -> mission.v1.Telemetry
	11, // 4: mission.v1.Mission.operator:type_name -> mission.v1.Operator
	12, // 5: mission.v1.Mission.launch_base:type_name -> mission.v1.LaunchBase
	13, // 6: mission.v1.Mission.drones:type_name -> mission.v1.Drone
	0,  // 7: mission.v1.MissionService.CreateMission:input_type -> mission.v1.CreateMissionRequest
	2,  // 8: mission.v1.MissionService.GetMission:input_type -> mission.v1.GetMissionRequest
	4,  // 9: mission.v1.MissionService.ListMissions:input_type -> mission.v1.ListMissionsRequest
	6,  // 10: mission.v1.MissionService.GetMissionTelemetry:input_type -> mission.v1.GetMissionTelemetryRequest
	8,  // 11: mission.v1.MissionService.WatchMission:input_type -> mission.v1.WatchMissionRequest
	1,  // 12: mission.v1.MissionService.CreateMission:output_type -> mission.v1.CreateMissionResponse
	3,  // 13: mission.v1.MissionService.GetMission:output_type -> mission.v1.GetMissionResponse
	5,  // 14: mission.v1.MissionService.ListMissions:output_type -> mission.v1.ListMissionsResponse
	7,  // 15: mission.v1.MissionService.GetMissionTelemetry:output_type -> mission.v1.GetMissionTelemetryResponse
	9,  // 16: mission.v1.MissionService.WatchMission:output_type -> mission.v1.MissionUpdate
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_mission_v1_mission_proto_init() }
func file_mission_v1_mission_proto_init() {
	if File_mission_v1_mission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mission_v1_mission_proto_rawDesc), len(file_mission_v1_mission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mission_v1_mission_proto_goTypes,
		DependencyIndexes: file_mission_v1_mission_proto_depIdxs,
		MessageInfos:      file_mission_v1_mission_proto_msgTypes,
	}.Build()
	File_mission_v1_mission_proto = out.File
	file_mission_v1_mission_proto_goTypes = nil
	file_mission_v1_mission_proto_depIdxs = nil
}
