// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: mission_api/mission.proto

package mission_api

import (
	models "github.com/Bolshevichok/dronedelivery/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertMissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Missions      []*models.Mission      `protobuf:"bytes,1,rep,name=missions,proto3" json:"missions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMissionsRequest) Reset() {
	*x = UpsertMissionsRequest{}
	mi := &file_mission_api_mission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMissionsRequest) ProtoMessage() {}

func (x *UpsertMissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMissionsRequest.ProtoReflect.Descriptor instead.
func (*UpsertMissionsRequest) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertMissionsRequest) GetMissions() []*models.Mission {
	if x != nil {
		return x.Missions
	}
	return nil
}

type UpsertMissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMissionsResponse) Reset() {
	*x = UpsertMissionsResponse{}
	mi := &file_mission_api_mission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMissionsResponse) ProtoMessage() {}

func (x *UpsertMissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMissionsResponse.ProtoReflect.Descriptor instead.
func (*UpsertMissionsResponse) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{1}
}

type GetMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionRequest) Reset() {
	*x = GetMissionRequest{}
	mi := &file_mission_api_mission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionRequest) ProtoMessage() {}

func (x *GetMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionRequest.ProtoReflect.Descriptor instead.
func (*GetMissionRequest) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{2}
}

func (x *GetMissionRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

type GetMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       *models.Mission        `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionResponse) Reset() {
	*x = GetMissionResponse{}
	mi := &file_mission_api_mission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionResponse) ProtoMessage() {}

func (x *GetMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionResponse.ProtoReflect.Descriptor instead.
func (*GetMissionResponse) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{3}
}

func (x *GetMissionResponse) GetMission() *models.Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

var File_mission_api_mission_proto protoreflect.FileDescriptor

const file_mission_api_mission_proto_rawDesc = "" +
	"\n" +
	"\x19mission_api/mission.proto\x12\vmission_api\x1a\x13models/models.proto\x1a\x1cgoogle/api/annotations.proto\"D\n" +
	"\x15UpsertMissionsRequest\x12+\n" +
	"\bmissions\x18\x01 \x03(\v2\x0f.models.MissionR\bmissions\"\x18\n" +
	"\x16UpsertMissionsResponse\"2\n" +
	"\x11GetMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\"?\n" +
	"\x12GetMissionResponse\x12)\n" +
	"\amission\x18\x01 \x01(\v2\x0f.models.MissionR\amission2\xf7\x01\n" +
	"\x0eMissionService\x12v\n" +
	"\x0eUpsertMissions\x12\".mission_api.UpsertMissionsRequest\x1a#.mission_api.UpsertMissionsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/missions/upsert\x12m\n" +
	"\n" +
	"GetMission\x12\x1e.mission_api.GetMissionRequest\x1a\x1f.mission_api.GetMissionResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/missions/{mission_id}B?Z=github.com/Bolshevichok/dronedelivery/internal/pb/mission_apib\x06proto3"

var (
	file_mission_api_mission_proto_rawDescOnce sync.Once
	file_mission_api_mission_proto_rawDescData []byte
)

func file_mission_api_mission_proto_rawDescGZIP() []byte {
	file_mission_api_mission_proto_rawDescOnce.Do(func() {
		file_mission_api_mission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mission_api_mission_proto_rawDesc), len(file_mission_api_mission_proto_rawDesc)))
	})
	return file_mission_api_mission_proto_rawDescData
}

var file_mission_api_mission_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mission_api_mission_proto_goTypes = []any{
	(*UpsertMissionsRequest)(nil),  // 0: mission_api.UpsertMissionsRequest
	(*UpsertMissionsResponse)(nil), // 1: mission_api.UpsertMissionsResponse
	(*GetMissionRequest)(nil),      // 2: mission_api.GetMissionRequest
	(*GetMissionResponse)(nil),     // 3: mission_api.GetMissionResponse
	(*models.Mission)(nil),         // 4: models.Mission
}
var file_mission_api_mission_proto_depIdxs = []int32{
	4, // 0: mission_api.UpsertMissionsRequest.missions:type_name -> models.Mission
	4, // 1: mission_api.GetMissionResponse.mission:type_name -> models.Mission
	0, // 2: mission_api.MissionService.UpsertMissions:input_type -> mission_api.UpsertMissionsRequest
	2, // 3: mission_api.MissionService.GetMission:input_type -> mission_api.GetMissionRequest
	1, // 4: mission_api.MissionService.UpsertMissions:output_type -> mission_api.UpsertMissionsResponse
	3, // 5: mission_api.MissionService.GetMission:output_type -> mission_api.GetMissionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mission_api_mission_proto_init() }
func file_mission_api_mission_proto_init() {
	if File_mission_api_mission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mission_api_mission_proto_rawDesc), len(file_mission_api_mission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mission_api_mission_proto_goTypes,
		DependencyIndexes: file_mission_api_mission_proto_depIdxs,
		MessageInfos:      file_mission_api_mission_proto_msgTypes,
	}.Build()
	File_mission_api_mission_proto = out.File
	file_mission_api_mission_proto_goTypes = nil
	file_mission_api_mission_proto_depIdxs = nil
}
