// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: mission_api/mission.proto

package mission_api

import (
	models "github.com/Bolshevichok/dronedelivery/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertMissionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated for multiple missions
	Missions      []*models.Mission `protobuf:"bytes,1,rep,name=missions,proto3" json:"missions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMissionsRequest) Reset() {
	*x = UpsertMissionsRequest{}
	mi := &file_mission_api_mission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMissionsRequest) ProtoMessage() {}

func (x *UpsertMissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMissionsRequest.ProtoReflect.Descriptor instead.
func (*UpsertMissionsRequest) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertMissionsRequest) GetMissions() []*models.Mission {
	if x != nil {
		return x.Missions
	}
	return nil
}

type UpsertMissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertMissionsResponse) Reset() {
	*x = UpsertMissionsResponse{}
	mi := &file_mission_api_mission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertMissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertMissionsResponse) ProtoMessage() {}

func (x *UpsertMissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertMissionsResponse.ProtoReflect.Descriptor instead.
func (*UpsertMissionsResponse) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{1}
}

type GetMissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MissionId     uint64                 `protobuf:"varint,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionRequest) Reset() {
	*x = GetMissionRequest{}
	mi := &file_mission_api_mission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionRequest) ProtoMessage() {}

func (x *GetMissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionRequest.ProtoReflect.Descriptor instead.
func (*GetMissionRequest) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{2}
}

func (x *GetMissionRequest) GetMissionId() uint64 {
	if x != nil {
		return x.MissionId
	}
	return 0
}

type GetMissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       *models.Mission        `protobuf:"bytes,1,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMissionResponse) Reset() {
	*x = GetMissionResponse{}
	mi := &file_mission_api_mission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMissionResponse) ProtoMessage() {}

func (x *GetMissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMissionResponse.ProtoReflect.Descriptor instead.
func (*GetMissionResponse) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{3}
}

func (x *GetMissionResponse) GetMission() *models.Mission {
	if x != nil {
		return x.Mission
	}
	return nil
}

type CreateOperatorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      *models.Operator       `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperatorRequest) Reset() {
	*x = CreateOperatorRequest{}
	mi := &file_mission_api_mission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperatorRequest) ProtoMessage() {}

func (x *CreateOperatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperatorRequest.ProtoReflect.Descriptor instead.
func (*CreateOperatorRequest) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOperatorRequest) GetOperator() *models.Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

type CreateOperatorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOperatorResponse) Reset() {
	*x = CreateOperatorResponse{}
	mi := &file_mission_api_mission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOperatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOperatorResponse) ProtoMessage() {}

func (x *CreateOperatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOperatorResponse.ProtoReflect.Descriptor instead.
func (*CreateOperatorResponse) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOperatorResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateLaunchBaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaunchBase    *models.LaunchBase     `protobuf:"bytes,1,opt,name=launch_base,json=launchBase,proto3" json:"launch_base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLaunchBaseRequest) Reset() {
	*x = CreateLaunchBaseRequest{}
	mi := &file_mission_api_mission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLaunchBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLaunchBaseRequest) ProtoMessage() {}

func (x *CreateLaunchBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLaunchBaseRequest.ProtoReflect.Descriptor instead.
func (*CreateLaunchBaseRequest) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{6}
}

func (x *CreateLaunchBaseRequest) GetLaunchBase() *models.LaunchBase {
	if x != nil {
		return x.LaunchBase
	}
	return nil
}

type CreateLaunchBaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLaunchBaseResponse) Reset() {
	*x = CreateLaunchBaseResponse{}
	mi := &file_mission_api_mission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLaunchBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLaunchBaseResponse) ProtoMessage() {}

func (x *CreateLaunchBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLaunchBaseResponse.ProtoReflect.Descriptor instead.
func (*CreateLaunchBaseResponse) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{7}
}

func (x *CreateLaunchBaseResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateDroneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drone         *models.Drone          `protobuf:"bytes,1,opt,name=drone,proto3" json:"drone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDroneRequest) Reset() {
	*x = CreateDroneRequest{}
	mi := &file_mission_api_mission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDroneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDroneRequest) ProtoMessage() {}

func (x *CreateDroneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDroneRequest.ProtoReflect.Descriptor instead.
func (*CreateDroneRequest) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{8}
}

func (x *CreateDroneRequest) GetDrone() *models.Drone {
	if x != nil {
		return x.Drone
	}
	return nil
}

type CreateDroneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDroneResponse) Reset() {
	*x = CreateDroneResponse{}
	mi := &file_mission_api_mission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDroneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDroneResponse) ProtoMessage() {}

func (x *CreateDroneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mission_api_mission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDroneResponse.ProtoReflect.Descriptor instead.
func (*CreateDroneResponse) Descriptor() ([]byte, []int) {
	return file_mission_api_mission_proto_rawDescGZIP(), []int{9}
}

func (x *CreateDroneResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_mission_api_mission_proto protoreflect.FileDescriptor

const file_mission_api_mission_proto_rawDesc = "" +
	"\n" +
	"\x19mission_api/mission.proto\x12\vmission_api\x1a\x13models/models.proto\x1a\x1cgoogle/api/annotations.proto\"D\n" +
	"\x15UpsertMissionsRequest\x12+\n" +
	"\bmissions\x18\x01 \x03(\v2\x0f.models.MissionR\bmissions\"\x18\n" +
	"\x16UpsertMissionsResponse\"2\n" +
	"\x11GetMissionRequest\x12\x1d\n" +
	"\n" +
	"mission_id\x18\x01 \x01(\x04R\tmissionId\"?\n" +
	"\x12GetMissionResponse\x12)\n" +
	"\amission\x18\x01 \x01(\v2\x0f.models.MissionR\amission\"E\n" +
	"\x15CreateOperatorRequest\x12,\n" +
	"\boperator\x18\x01 \x01(\v2\x10.models.OperatorR\boperator\"(\n" +
	"\x16CreateOperatorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"N\n" +
	"\x17CreateLaunchBaseRequest\x123\n" +
	"\vlaunch_base\x18\x01 \x01(\v2\x12.models.LaunchBaseR\n" +
	"launchBase\"*\n" +
	"\x18CreateLaunchBaseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"9\n" +
	"\x12CreateDroneRequest\x12#\n" +
	"\x05drone\x18\x01 \x01(\v2\r.models.DroneR\x05drone\"%\n" +
	"\x13CreateDroneResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id2\xca\x04\n" +
	"\x0eMissionService\x12v\n" +
	"\x0eUpsertMissions\x12\".mission_api.UpsertMissionsRequest\x1a#.mission_api.UpsertMissionsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/missions/upsert\x12m\n" +
	"\n" +
	"GetMission\x12\x1e.mission_api.GetMissionRequest\x1a\x1f.mission_api.GetMissionResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/missions/{mission_id}\x12p\n" +
	"\x0eCreateOperator\x12\".mission_api.CreateOperatorRequest\x1a#.mission_api.CreateOperatorResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/operators\x12y\n" +
	"\x10CreateLaunchBase\x12$.mission_api.CreateLaunchBaseRequest\x1a%.mission_api.CreateLaunchBaseResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/launch-bases\x12d\n" +
	"\vCreateDrone\x12\x1f.mission_api.CreateDroneRequest\x1a .mission_api.CreateDroneResponse\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/dronesB?Z=github.com/Bolshevichok/dronedelivery/internal/pb/mission_apib\x06proto3"

var (
	file_mission_api_mission_proto_rawDescOnce sync.Once
	file_mission_api_mission_proto_rawDescData []byte
)

func file_mission_api_mission_proto_rawDescGZIP() []byte {
	file_mission_api_mission_proto_rawDescOnce.Do(func() {
		file_mission_api_mission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mission_api_mission_proto_rawDesc), len(file_mission_api_mission_proto_rawDesc)))
	})
	return file_mission_api_mission_proto_rawDescData
}

var file_mission_api_mission_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mission_api_mission_proto_goTypes = []any{
	(*UpsertMissionsRequest)(nil),    // 0: mission_api.UpsertMissionsRequest
	(*UpsertMissionsResponse)(nil),   // 1: mission_api.UpsertMissionsResponse
	(*GetMissionRequest)(nil),        // 2: mission_api.GetMissionRequest
	(*GetMissionResponse)(nil),       // 3: mission_api.GetMissionResponse
	(*CreateOperatorRequest)(nil),    // 4: mission_api.CreateOperatorRequest
	(*CreateOperatorResponse)(nil),   // 5: mission_api.CreateOperatorResponse
	(*CreateLaunchBaseRequest)(nil),  // 6: mission_api.CreateLaunchBaseRequest
	(*CreateLaunchBaseResponse)(nil), // 7: mission_api.CreateLaunchBaseResponse
	(*CreateDroneRequest)(nil),       // 8: mission_api.CreateDroneRequest
	(*CreateDroneResponse)(nil),      // 9: mission_api.CreateDroneResponse
	(*models.Mission)(nil),           // 10: models.Mission
	(*models.Operator)(nil),          // 11: models.Operator
	(*models.LaunchBase)(nil),        // 12: models.LaunchBase
	(*models.Drone)(nil),             // 13: models.Drone
}
var file_mission_api_mission_proto_depIdxs = []int32{
	10, // 0: mission_api.UpsertMissionsRequest.missions:type_name -> models.Mission
	10, // 1: mission_api.GetMissionResponse.mission:type_name -> models.Mission
	11, // 2: mission_api.CreateOperatorRequest.operator:type_name -> models.Operator
	12, // 3: mission_api.CreateLaunchBaseRequest.launch_base:type_name -> models.LaunchBase
	13, // 4: mission_api.CreateDroneRequest.drone:type_name -> models.Drone
	0,  // 5: mission_api.MissionService.UpsertMissions:input_type -> mission_api.UpsertMissionsRequest
	2,  // 6: mission_api.MissionService.GetMission:input_type -> mission_api.GetMissionRequest
	4,  // 7: mission_api.MissionService.CreateOperator:input_type -> mission_api.CreateOperatorRequest
	6,  // 8: mission_api.MissionService.CreateLaunchBase:input_type -> mission_api.CreateLaunchBaseRequest
	8,  // 9: mission_api.MissionService.CreateDrone:input_type -> mission_api.CreateDroneRequest
	1,  // 10: mission_api.MissionService.UpsertMissions:output_type -> mission_api.UpsertMissionsResponse
	3,  // 11: mission_api.MissionService.GetMission:output_type -> mission_api.GetMissionResponse
	5,  // 12: mission_api.MissionService.CreateOperator:output_type -> mission_api.CreateOperatorResponse
	7,  // 13: mission_api.MissionService.CreateLaunchBase:output_type -> mission_api.CreateLaunchBaseResponse
	9,  // 14: mission_api.MissionService.CreateDrone:output_type -> mission_api.CreateDroneResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_mission_api_mission_proto_init() }
func file_mission_api_mission_proto_init() {
	if File_mission_api_mission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mission_api_mission_proto_rawDesc), len(file_mission_api_mission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mission_api_mission_proto_goTypes,
		DependencyIndexes: file_mission_api_mission_proto_depIdxs,
		MessageInfos:      file_mission_api_mission_proto_msgTypes,
	}.Build()
	File_mission_api_mission_proto = out.File
	file_mission_api_mission_proto_goTypes = nil
	file_mission_api_mission_proto_depIdxs = nil
}
