// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: models/models.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OpId          uint64                 `protobuf:"varint,2,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	BaseId        uint64                 `protobuf:"varint,3,opt,name=base_id,json=baseId,proto3" json:"base_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Lat           float64                `protobuf:"fixed64,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,6,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,7,opt,name=alt,proto3" json:"alt,omitempty"`
	Payload       float64                `protobuf:"fixed64,8,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mission) Reset() {
	*x = Mission{}
	mi := &file_models_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{0}
}

func (x *Mission) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mission) GetOpId() uint64 {
	if x != nil {
		return x.OpId
	}
	return 0
}

func (x *Mission) GetBaseId() uint64 {
	if x != nil {
		return x.BaseId
	}
	return 0
}

func (x *Mission) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Mission) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Mission) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Mission) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Mission) GetPayload() float64 {
	if x != nil {
		return x.Payload
	}
	return 0
}

func (x *Mission) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Operator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operator) Reset() {
	*x = Operator{}
	mi := &file_models_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{1}
}

func (x *Operator) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Operator) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Operator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operator) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type LaunchBase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,4,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,5,opt,name=alt,proto3" json:"alt,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchBase) Reset() {
	*x = LaunchBase{}
	mi := &file_models_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchBase) ProtoMessage() {}

func (x *LaunchBase) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchBase.ProtoReflect.Descriptor instead.
func (*LaunchBase) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{2}
}

func (x *LaunchBase) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LaunchBase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LaunchBase) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LaunchBase) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *LaunchBase) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *LaunchBase) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Drone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Serial        string                 `protobuf:"bytes,2,opt,name=serial,proto3" json:"serial,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	BaseId        uint64                 `protobuf:"varint,5,opt,name=base_id,json=baseId,proto3" json:"base_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drone) Reset() {
	*x = Drone{}
	mi := &file_models_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drone) ProtoMessage() {}

func (x *Drone) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drone.ProtoReflect.Descriptor instead.
func (*Drone) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{3}
}

func (x *Drone) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Drone) GetSerial() string {
	if x != nil {
		return x.Serial
	}
	return ""
}

func (x *Drone) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Drone) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Drone) GetBaseId() uint64 {
	if x != nil {
		return x.BaseId
	}
	return 0
}

func (x *Drone) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type Telemetry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DroneId       uint64                 `protobuf:"varint,1,opt,name=drone_id,json=droneId,proto3" json:"drone_id,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Alt           float64                `protobuf:"fixed64,4,opt,name=alt,proto3" json:"alt,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_models_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_models_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_models_models_proto_rawDescGZIP(), []int{4}
}

func (x *Telemetry) GetDroneId() uint64 {
	if x != nil {
		return x.DroneId
	}
	return 0
}

func (x *Telemetry) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Telemetry) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Telemetry) GetAlt() float64 {
	if x != nil {
		return x.Alt
	}
	return 0
}

func (x *Telemetry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_models_models_proto protoreflect.FileDescriptor

const file_models_models_proto_rawDesc = "" +
	"\n" +
	"\x13models/models.proto\x12\x06models\"\xce\x01\n" +
	"\aMission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x13\n" +
	"\x05op_id\x18\x02 \x01(\x04R\x04opId\x12\x17\n" +
	"\abase_id\x18\x03 \x01(\x04R\x06baseId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x10\n" +
	"\x03lat\x18\x05 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x06 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\a \x01(\x01R\x03alt\x12\x18\n" +
	"\apayload\x18\b \x01(\x01R\apayload\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"c\n" +
	"\bOperator\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"\x85\x01\n" +
	"\n" +
	"LaunchBase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x04 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x05 \x01(\x01R\x03alt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x95\x01\n" +
	"\x05Drone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06serial\x18\x02 \x01(\tR\x06serial\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x17\n" +
	"\abase_id\x18\x05 \x01(\x04R\x06baseId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"z\n" +
	"\tTelemetry\x12\x19\n" +
	"\bdrone_id\x18\x01 \x01(\x04R\adroneId\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x10\n" +
	"\x03alt\x18\x04 \x01(\x01R\x03alt\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestampB:Z8github.com/Bolshevichok/dronedelivery/internal/pb/modelsb\x06proto3"

var (
	file_models_models_proto_rawDescOnce sync.Once
	file_models_models_proto_rawDescData []byte
)

func file_models_models_proto_rawDescGZIP() []byte {
	file_models_models_proto_rawDescOnce.Do(func() {
		file_models_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_models_proto_rawDesc), len(file_models_models_proto_rawDesc)))
	})
	return file_models_models_proto_rawDescData
}

var file_models_models_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_models_models_proto_goTypes = []any{
	(*Mission)(nil),    // 0: models.Mission
	(*Operator)(nil),   // 1: models.Operator
	(*LaunchBase)(nil), // 2: models.LaunchBase
	(*Drone)(nil),      // 3: models.Drone
	(*Telemetry)(nil),  // 4: models.Telemetry
}
var file_models_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_models_proto_init() }
func file_models_models_proto_init() {
	if File_models_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_models_proto_rawDesc), len(file_models_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_models_proto_goTypes,
		DependencyIndexes: file_models_models_proto_depIdxs,
		MessageInfos:      file_models_models_proto_msgTypes,
	}.Build()
	File_models_models_proto = out.File
	file_models_models_proto_goTypes = nil
	file_models_models_proto_depIdxs = nil
}
