// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: mission/v1/mission.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MissionService_CreateMission_FullMethodName       = "/mission.v1.MissionService/CreateMission"
	MissionService_GetMission_FullMethodName          = "/mission.v1.MissionService/GetMission"
	MissionService_ListMissions_FullMethodName        = "/mission.v1.MissionService/ListMissions"
	MissionService_GetMissionTelemetry_FullMethodName = "/mission.v1.MissionService/GetMissionTelemetry"
	MissionService_WatchMission_FullMethodName        = "/mission.v1.MissionService/WatchMission"
)

// MissionServiceClient is the client API for MissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MissionServiceClient interface {
	CreateMission(ctx context.Context, in *CreateMissionRequest, opts ...grpc.CallOption) (*CreateMissionResponse, error)
	GetMission(ctx context.Context, in *GetMissionRequest, opts ...grpc.CallOption) (*GetMissionResponse, error)
	ListMissions(ctx context.Context, in *ListMissionsRequest, opts ...grpc.CallOption) (*ListMissionsResponse, error)
	GetMissionTelemetry(ctx context.Context, in *GetMissionTelemetryRequest, opts ...grpc.CallOption) (*GetMissionTelemetryResponse, error)
	WatchMission(ctx context.Context, in *WatchMissionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MissionUpdate], error)
}

type missionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMissionServiceClient(cc grpc.ClientConnInterface) MissionServiceClient {
	return &missionServiceClient{cc}
}

func (c *missionServiceClient) CreateMission(ctx context.Context, in *CreateMissionRequest, opts ...grpc.CallOption) (*CreateMissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMissionResponse)
	err := c.cc.Invoke(ctx, MissionService_CreateMission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionServiceClient) GetMission(ctx context.Context, in *GetMissionRequest, opts ...grpc.CallOption) (*GetMissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMissionResponse)
	err := c.cc.Invoke(ctx, MissionService_GetMission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionServiceClient) ListMissions(ctx context.Context, in *ListMissionsRequest, opts ...grpc.CallOption) (*ListMissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMissionsResponse)
	err := c.cc.Invoke(ctx, MissionService_ListMissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionServiceClient) GetMissionTelemetry(ctx context.Context, in *GetMissionTelemetryRequest, opts ...grpc.CallOption) (*GetMissionTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMissionTelemetryResponse)
	err := c.cc.Invoke(ctx, MissionService_GetMissionTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionServiceClient) WatchMission(ctx context.Context, in *WatchMissionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MissionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MissionService_ServiceDesc.Streams[0], MissionService_WatchMission_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchMissionRequest, MissionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MissionService_WatchMissionClient = grpc.ServerStreamingClient[MissionUpdate]

// MissionServiceServer is the server API for MissionService service.
// All implementations must embed UnimplementedMissionServiceServer
// for forward compatibility.
type MissionServiceServer interface {
	CreateMission(context.Context, *CreateMissionRequest) (*CreateMissionResponse, error)
	GetMission(context.Context, *GetMissionRequest) (*GetMissionResponse, error)
	ListMissions(context.Context, *ListMissionsRequest) (*ListMissionsResponse, error)
	GetMissionTelemetry(context.Context, *GetMissionTelemetryRequest) (*GetMissionTelemetryResponse, error)
	WatchMission(*WatchMissionRequest, grpc.ServerStreamingServer[MissionUpdate]) error
	mustEmbedUnimplementedMissionServiceServer()
}

// UnimplementedMissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMissionServiceServer struct{}

func (UnimplementedMissionServiceServer) CreateMission(context.Context, *CreateMissionRequest) (*CreateMissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMission not implemented")
}
func (UnimplementedMissionServiceServer) GetMission(context.Context, *GetMissionRequest) (*GetMissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMission not implemented")
}
func (UnimplementedMissionServiceServer) ListMissions(context.Context, *ListMissionsRequest) (*ListMissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMissions not implemented")
}
func (UnimplementedMissionServiceServer) GetMissionTelemetry(context.Context, *GetMissionTelemetryRequest) (*GetMissionTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMissionTelemetry not implemented")
}
func (UnimplementedMissionServiceServer) WatchMission(*WatchMissionRequest, grpc.ServerStreamingServer[MissionUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchMission not implemented")
}
func (UnimplementedMissionServiceServer) mustEmbedUnimplementedMissionServiceServer() {}
func (UnimplementedMissionServiceServer) testEmbeddedByValue()                        {}

// UnsafeMissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MissionServiceServer will
// result in compilation errors.
type UnsafeMissionServiceServer interface {
	mustEmbedUnimplementedMissionServiceServer()
}

func RegisterMissionServiceServer(s grpc.ServiceRegistrar, srv MissionServiceServer) {
	// If the following call panics, it indicates UnimplementedMissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MissionService_ServiceDesc, srv)
}

func _MissionService_CreateMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServiceServer).CreateMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MissionService_CreateMission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServiceServer).CreateMission(ctx, req.(*CreateMissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MissionService_GetMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServiceServer).GetMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MissionService_GetMission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServiceServer).GetMission(ctx, req.(*GetMissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MissionService_ListMissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServiceServer).ListMissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MissionService_ListMissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServiceServer).ListMissions(ctx, req.(*ListMissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MissionService_GetMissionTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMissionTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionServiceServer).GetMissionTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MissionService_GetMissionTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionServiceServer).GetMissionTelemetry(ctx, req.(*GetMissionTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MissionService_WatchMission_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchMissionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MissionServiceServer).WatchMission(m, &grpc.GenericServerStream[WatchMissionRequest, MissionUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MissionService_WatchMissionServer = grpc.ServerStreamingServer[MissionUpdate]

// MissionService_ServiceDesc is the grpc.ServiceDesc for MissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mission.v1.MissionService",
	HandlerType: (*MissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMission",
			Handler:    _MissionService_CreateMission_Handler,
		},
		{
			MethodName: "GetMission",
			Handler:    _MissionService_GetMission_Handler,
		},
		{
			MethodName: "ListMissions",
			Handler:    _MissionService_ListMissions_Handler,
		},
		{
			MethodName: "GetMissionTelemetry",
			Handler:    _MissionService_GetMissionTelemetry_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchMission",
			Handler:       _MissionService_WatchMission_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mission/v1/mission.proto",
}
