// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/Bolshevichok/dronedelivery/internal/models"
)

// MockMissionStorage is an autogenerated mock type for the MissionStorage type
type MockMissionStorage struct {
	mock.Mock
}

type MockMissionStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMissionStorage) EXPECT() *MockMissionStorage_Expecter {
	return &MockMissionStorage_Expecter{mock: &_m.Mock}
}

// CreateDrone provides a mock function with given fields: ctx, drone
func (_m *MockMissionStorage) CreateDrone(ctx context.Context, drone *models.Drone) (uint64, error) {
	ret := _m.Called(ctx, drone)

	if len(ret) == 0 {
		panic("no return value specified for CreateDrone")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Drone) (uint64, error)); ok {
		return rf(ctx, drone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Drone) uint64); ok {
		r0 = rf(ctx, drone)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Drone) error); ok {
		r1 = rf(ctx, drone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMissionStorage_CreateDrone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDrone'
type MockMissionStorage_CreateDrone_Call struct {
	*mock.Call
}

// CreateDrone is a helper method to define mock.On call
//   - ctx context.Context
//   - drone *models.Drone
func (_e *MockMissionStorage_Expecter) CreateDrone(ctx interface{}, drone interface{}) *MockMissionStorage_CreateDrone_Call {
	return &MockMissionStorage_CreateDrone_Call{Call: _e.mock.On("CreateDrone", ctx, drone)}
}

func (_c *MockMissionStorage_CreateDrone_Call) Run(run func(ctx context.Context, drone *models.Drone)) *MockMissionStorage_CreateDrone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Drone))
	})
	return _c
}

func (_c *MockMissionStorage_CreateDrone_Call) Return(_a0 uint64, _a1 error) *MockMissionStorage_CreateDrone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMissionStorage_CreateDrone_Call) RunAndReturn(run func(context.Context, *models.Drone) (uint64, error)) *MockMissionStorage_CreateDrone_Call {
	_c.Call.Return(run)
	return _c
}

// CreateLaunchBase provides a mock function with given fields: ctx, launchBase
func (_m *MockMissionStorage) CreateLaunchBase(ctx context.Context, launchBase *models.LaunchBase) (uint64, error) {
	ret := _m.Called(ctx, launchBase)

	if len(ret) == 0 {
		panic("no return value specified for CreateLaunchBase")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LaunchBase) (uint64, error)); ok {
		return rf(ctx, launchBase)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.LaunchBase) uint64); ok {
		r0 = rf(ctx, launchBase)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.LaunchBase) error); ok {
		r1 = rf(ctx, launchBase)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMissionStorage_CreateLaunchBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateLaunchBase'
type MockMissionStorage_CreateLaunchBase_Call struct {
	*mock.Call
}

// CreateLaunchBase is a helper method to define mock.On call
//   - ctx context.Context
//   - launchBase *models.LaunchBase
func (_e *MockMissionStorage_Expecter) CreateLaunchBase(ctx interface{}, launchBase interface{}) *MockMissionStorage_CreateLaunchBase_Call {
	return &MockMissionStorage_CreateLaunchBase_Call{Call: _e.mock.On("CreateLaunchBase", ctx, launchBase)}
}

func (_c *MockMissionStorage_CreateLaunchBase_Call) Run(run func(ctx context.Context, launchBase *models.LaunchBase)) *MockMissionStorage_CreateLaunchBase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.LaunchBase))
	})
	return _c
}

func (_c *MockMissionStorage_CreateLaunchBase_Call) Return(_a0 uint64, _a1 error) *MockMissionStorage_CreateLaunchBase_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMissionStorage_CreateLaunchBase_Call) RunAndReturn(run func(context.Context, *models.LaunchBase) (uint64, error)) *MockMissionStorage_CreateLaunchBase_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOperator provides a mock function with given fields: ctx, operator
func (_m *MockMissionStorage) CreateOperator(ctx context.Context, operator *models.Operator) (uint64, error) {
	ret := _m.Called(ctx, operator)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperator")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Operator) (uint64, error)); ok {
		return rf(ctx, operator)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Operator) uint64); ok {
		r0 = rf(ctx, operator)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Operator) error); ok {
		r1 = rf(ctx, operator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMissionStorage_CreateOperator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOperator'
type MockMissionStorage_CreateOperator_Call struct {
	*mock.Call
}

// CreateOperator is a helper method to define mock.On call
//   - ctx context.Context
//   - operator *models.Operator
func (_e *MockMissionStorage_Expecter) CreateOperator(ctx interface{}, operator interface{}) *MockMissionStorage_CreateOperator_Call {
	return &MockMissionStorage_CreateOperator_Call{Call: _e.mock.On("CreateOperator", ctx, operator)}
}

func (_c *MockMissionStorage_CreateOperator_Call) Run(run func(ctx context.Context, operator *models.Operator)) *MockMissionStorage_CreateOperator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Operator))
	})
	return _c
}

func (_c *MockMissionStorage_CreateOperator_Call) Return(_a0 uint64, _a1 error) *MockMissionStorage_CreateOperator_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMissionStorage_CreateOperator_Call) RunAndReturn(run func(context.Context, *models.Operator) (uint64, error)) *MockMissionStorage_CreateOperator_Call {
	_c.Call.Return(run)
	return _c
}

// GetDronesByIDs provides a mock function with given fields: ctx, IDs
func (_m *MockMissionStorage) GetDronesByIDs(ctx context.Context, IDs []uint64) ([]*models.Drone, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetDronesByIDs")
	}

	var r0 []*models.Drone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.Drone, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.Drone); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Drone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMissionStorage_GetDronesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDronesByIDs'
type MockMissionStorage_GetDronesByIDs_Call struct {
	*mock.Call
}

// GetDronesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uint64
func (_e *MockMissionStorage_Expecter) GetDronesByIDs(ctx interface{}, IDs interface{}) *MockMissionStorage_GetDronesByIDs_Call {
	return &MockMissionStorage_GetDronesByIDs_Call{Call: _e.mock.On("GetDronesByIDs", ctx, IDs)}
}

func (_c *MockMissionStorage_GetDronesByIDs_Call) Run(run func(ctx context.Context, IDs []uint64)) *MockMissionStorage_GetDronesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *MockMissionStorage_GetDronesByIDs_Call) Return(_a0 []*models.Drone, _a1 error) *MockMissionStorage_GetDronesByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMissionStorage_GetDronesByIDs_Call) RunAndReturn(run func(context.Context, []uint64) ([]*models.Drone, error)) *MockMissionStorage_GetDronesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetLaunchBasesByIDs provides a mock function with given fields: ctx, IDs
func (_m *MockMissionStorage) GetLaunchBasesByIDs(ctx context.Context, IDs []uint64) ([]*models.LaunchBase, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetLaunchBasesByIDs")
	}

	var r0 []*models.LaunchBase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.LaunchBase, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.LaunchBase); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.LaunchBase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMissionStorage_GetLaunchBasesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLaunchBasesByIDs'
type MockMissionStorage_GetLaunchBasesByIDs_Call struct {
	*mock.Call
}

// GetLaunchBasesByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uint64
func (_e *MockMissionStorage_Expecter) GetLaunchBasesByIDs(ctx interface{}, IDs interface{}) *MockMissionStorage_GetLaunchBasesByIDs_Call {
	return &MockMissionStorage_GetLaunchBasesByIDs_Call{Call: _e.mock.On("GetLaunchBasesByIDs", ctx, IDs)}
}

func (_c *MockMissionStorage_GetLaunchBasesByIDs_Call) Run(run func(ctx context.Context, IDs []uint64)) *MockMissionStorage_GetLaunchBasesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *MockMissionStorage_GetLaunchBasesByIDs_Call) Return(_a0 []*models.LaunchBase, _a1 error) *MockMissionStorage_GetLaunchBasesByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMissionStorage_GetLaunchBasesByIDs_Call) RunAndReturn(run func(context.Context, []uint64) ([]*models.LaunchBase, error)) *MockMissionStorage_GetLaunchBasesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetMissionDronesByMissionID provides a mock function with given fields: ctx, missionID
func (_m *MockMissionStorage) GetMissionDronesByMissionID(ctx context.Context, missionID uint64) ([]*models.MissionDrone, error) {
	ret := _m.Called(ctx, missionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMissionDronesByMissionID")
	}

	var r0 []*models.MissionDrone
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]*models.MissionDrone, error)); ok {
		return rf(ctx, missionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []*models.MissionDrone); ok {
		r0 = rf(ctx, missionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.MissionDrone)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, missionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMissionStorage_GetMissionDronesByMissionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMissionDronesByMissionID'
type MockMissionStorage_GetMissionDronesByMissionID_Call struct {
	*mock.Call
}

// GetMissionDronesByMissionID is a helper method to define mock.On call
//   - ctx context.Context
//   - missionID uint64
func (_e *MockMissionStorage_Expecter) GetMissionDronesByMissionID(ctx interface{}, missionID interface{}) *MockMissionStorage_GetMissionDronesByMissionID_Call {
	return &MockMissionStorage_GetMissionDronesByMissionID_Call{Call: _e.mock.On("GetMissionDronesByMissionID", ctx, missionID)}
}

func (_c *MockMissionStorage_GetMissionDronesByMissionID_Call) Run(run func(ctx context.Context, missionID uint64)) *MockMissionStorage_GetMissionDronesByMissionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockMissionStorage_GetMissionDronesByMissionID_Call) Return(_a0 []*models.MissionDrone, _a1 error) *MockMissionStorage_GetMissionDronesByMissionID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMissionStorage_GetMissionDronesByMissionID_Call) RunAndReturn(run func(context.Context, uint64) ([]*models.MissionDrone, error)) *MockMissionStorage_GetMissionDronesByMissionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMissionsByIDs provides a mock function with given fields: ctx, IDs
func (_m *MockMissionStorage) GetMissionsByIDs(ctx context.Context, IDs []uint64) ([]*models.Mission, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetMissionsByIDs")
	}

	var r0 []*models.Mission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.Mission, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.Mission); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Mission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMissionStorage_GetMissionsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMissionsByIDs'
type MockMissionStorage_GetMissionsByIDs_Call struct {
	*mock.Call
}

// GetMissionsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uint64
func (_e *MockMissionStorage_Expecter) GetMissionsByIDs(ctx interface{}, IDs interface{}) *MockMissionStorage_GetMissionsByIDs_Call {
	return &MockMissionStorage_GetMissionsByIDs_Call{Call: _e.mock.On("GetMissionsByIDs", ctx, IDs)}
}

func (_c *MockMissionStorage_GetMissionsByIDs_Call) Run(run func(ctx context.Context, IDs []uint64)) *MockMissionStorage_GetMissionsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *MockMissionStorage_GetMissionsByIDs_Call) Return(_a0 []*models.Mission, _a1 error) *MockMissionStorage_GetMissionsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMissionStorage_GetMissionsByIDs_Call) RunAndReturn(run func(context.Context, []uint64) ([]*models.Mission, error)) *MockMissionStorage_GetMissionsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperatorsByIDs provides a mock function with given fields: ctx, IDs
func (_m *MockMissionStorage) GetOperatorsByIDs(ctx context.Context, IDs []uint64) ([]*models.Operator, error) {
	ret := _m.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for GetOperatorsByIDs")
	}

	var r0 []*models.Operator
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) ([]*models.Operator, error)); ok {
		return rf(ctx, IDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint64) []*models.Operator); ok {
		r0 = rf(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Operator)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint64) error); ok {
		r1 = rf(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMissionStorage_GetOperatorsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperatorsByIDs'
type MockMissionStorage_GetOperatorsByIDs_Call struct {
	*mock.Call
}

// GetOperatorsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uint64
func (_e *MockMissionStorage_Expecter) GetOperatorsByIDs(ctx interface{}, IDs interface{}) *MockMissionStorage_GetOperatorsByIDs_Call {
	return &MockMissionStorage_GetOperatorsByIDs_Call{Call: _e.mock.On("GetOperatorsByIDs", ctx, IDs)}
}

func (_c *MockMissionStorage_GetOperatorsByIDs_Call) Run(run func(ctx context.Context, IDs []uint64)) *MockMissionStorage_GetOperatorsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint64))
	})
	return _c
}

func (_c *MockMissionStorage_GetOperatorsByIDs_Call) Return(_a0 []*models.Operator, _a1 error) *MockMissionStorage_GetOperatorsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMissionStorage_GetOperatorsByIDs_Call) RunAndReturn(run func(context.Context, []uint64) ([]*models.Operator, error)) *MockMissionStorage_GetOperatorsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMissionStatus provides a mock function with given fields: ctx, missionID, status
func (_m *MockMissionStorage) UpdateMissionStatus(ctx context.Context, missionID uint64, status string) error {
	ret := _m.Called(ctx, missionID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMissionStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, string) error); ok {
		r0 = rf(ctx, missionID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMissionStorage_UpdateMissionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMissionStatus'
type MockMissionStorage_UpdateMissionStatus_Call struct {
	*mock.Call
}

// UpdateMissionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - missionID uint64
//   - status string
func (_e *MockMissionStorage_Expecter) UpdateMissionStatus(ctx interface{}, missionID interface{}, status interface{}) *MockMissionStorage_UpdateMissionStatus_Call {
	return &MockMissionStorage_UpdateMissionStatus_Call{Call: _e.mock.On("UpdateMissionStatus", ctx, missionID, status)}
}

func (_c *MockMissionStorage_UpdateMissionStatus_Call) Run(run func(ctx context.Context, missionID uint64, status string)) *MockMissionStorage_UpdateMissionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(string))
	})
	return _c
}

func (_c *MockMissionStorage_UpdateMissionStatus_Call) Return(_a0 error) *MockMissionStorage_UpdateMissionStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMissionStorage_UpdateMissionStatus_Call) RunAndReturn(run func(context.Context, uint64, string) error) *MockMissionStorage_UpdateMissionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertMissions provides a mock function with given fields: ctx, missions
func (_m *MockMissionStorage) UpsertMissions(ctx context.Context, missions []*models.Mission) ([]*models.Mission, error) {
	ret := _m.Called(ctx, missions)

	if len(ret) == 0 {
		panic("no return value specified for UpsertMissions")
	}

	var r0 []*models.Mission
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Mission) ([]*models.Mission, error)); ok {
		return rf(ctx, missions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Mission) []*models.Mission); ok {
		r0 = rf(ctx, missions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Mission)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*models.Mission) error); ok {
		r1 = rf(ctx, missions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMissionStorage_UpsertMissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertMissions'
type MockMissionStorage_UpsertMissions_Call struct {
	*mock.Call
}

// UpsertMissions is a helper method to define mock.On call
//   - ctx context.Context
//   - missions []*models.Mission
func (_e *MockMissionStorage_Expecter) UpsertMissions(ctx interface{}, missions interface{}) *MockMissionStorage_UpsertMissions_Call {
	return &MockMissionStorage_UpsertMissions_Call{Call: _e.mock.On("UpsertMissions", ctx, missions)}
}

func (_c *MockMissionStorage_UpsertMissions_Call) Run(run func(ctx context.Context, missions []*models.Mission)) *MockMissionStorage_UpsertMissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*models.Mission))
	})
	return _c
}

func (_c *MockMissionStorage_UpsertMissions_Call) Return(_a0 []*models.Mission, _a1 error) *MockMissionStorage_UpsertMissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMissionStorage_UpsertMissions_Call) RunAndReturn(run func(context.Context, []*models.Mission) ([]*models.Mission, error)) *MockMissionStorage_UpsertMissions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMissionStorage creates a new instance of MockMissionStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMissionStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMissionStorage {
	mock := &MockMissionStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
